apiVersion: v1
kind: Service
metadata:
  name: hk-hotels-frontend
  namespace: hk-hotels
  labels:
    app: hk-hotels
    component: frontend
spec:
  selector:
    app: hk-hotels
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP