apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hk-hotels

resources:
  - namespace.yaml
  - configmap.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app: hk-hotels
  managed-by: kustomize

commonAnnotations:
  description: "HK Hotels Frontend - Sistema de gestión hotelera"
  repository: "https://github.com/MarioAran/HkHotels"

images:
  - name: hk-hotels-frontend
    newName: ghcr.io/marioaran/hkhotelsfront
    newTag: latest